server:
  http:
    addr: 0.0.0.0:8000
    timeout: 2s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 2s
data:
  database:
    table_name: "leaf_alloc"
    driver: mysql
    source: root:123@tcp(127.0.0.1:3306)/leaf?charset=utf8&parseTime=True&loc=Local
    open_conn: 50
    idle: 10
    idle_timeout: 14400s
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
